---
# .pre-commit-config.yml
# Pre-commit hook tasks.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
      - id: ruff
        args:
          - --exit-non-zero-on-fix
  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyyaml==6.0.12.12
          - types-requests==2.31.0.10
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        additional_dependencies:
          - poetry-plugin-export==1.6.0
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
