---
# .pre-commit-config.yml
# Pre-commit hook tasks.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyyaml==6.0.12.12
          - types-requests==2.31.0.10
  - repo: https://github.com/pdm-project/pdm
    rev: "2.13.2"
    hooks:
      - id: pdm-lock-check
