name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Build source distribution and wheels
        run: pdm build --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 5
          if-no-files-found: error

  publish-pypi:
    needs: build
    runs-on: ubuntu-22.04
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Publish to PyPI
        run: pdm publish --no-build --verbose

  publish-github-release:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: dist/*
          release_id: ${{ github.event.release.id }}
          overwrite: true
